
site_name: Modeling Fabric
site_url: https://lynker-spatial.github.io/hfdatamodel/

theme:
  name: material
  logo: branding/logo.svg
  custom_dir: overrides

extra_css:
  - css/flowfabric-brand.css

nav:
  - Home: index.md
  - Data model: data_model.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - diagrams

