site_name: Modeling Fabric
site_url: https://lynker-spatial.github.io/hfdatamodel/

theme:
  name: material

nav:
  - Home: index.md
  - Data model: data_model.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - diagrams

